export const metadata = {
  title: "Terms",
  description: "Brewmate terms of service.",
};

const updated = "2026-05-11";

export default function TermsPage() {
  return (
    <article className="space-y-6">
      <header className="border-b border-rule pb-6">
        <div className="eyebrow mb-3">terms · 利用規約</div>
        <h1 className="display text-4xl md:text-5xl mb-2">Terms of Service</h1>
        <p className="font-mono text-[11px] uppercase tracking-widest text-ink-2">last updated · {updated}</p>
      </header>

      <Prose>
        <p>
          By using Brewmate (the “Service”), you agree to these terms. If you disagree, please don&apos;t use it.
        </p>

        <H2>The service</H2>
        <p>
          Brewmate is a journal for home coffee brewing, with AI-generated tasting feedback. It&apos;s offered as-is,
          on a best-effort basis. There&apos;s no SLA; downtime can happen; AI suggestions are <i>suggestions</i>, not advice.
        </p>

        <H2>Your account</H2>
        <p>
          You&apos;re responsible for keeping your Google account secure. You can sign up and delete your account at any time.
          We can suspend an account that is being used to abuse the service (e.g., scraping, exceeding rate limits, attacking
          infrastructure).
        </p>

        <H2>Your content</H2>
        <p>
          You retain ownership of the brew data you put into Brewmate. You grant us a non-exclusive license to store and
          process it solely to provide the service to you (including sending the necessary parts to the AI provider).
        </p>

        <H2>Rate limits</H2>
        <p>
          The app applies daily caps to prevent abuse — currently 200 brew logs per user per day, and a separate daily cap
          on AI suggestion calls. These can change as the service evolves; we&apos;ll surface changes in-app.
        </p>

        <H2>AI output</H2>
        <p>
          AI tasting suggestions are generated by third-party models and may be wrong, incomplete, or odd. Use your own
          judgement. We are not liable for a bad brew.
        </p>

        <H2>Acceptable use</H2>
        <ul>
          <li>No attempts to bypass authentication, rate limits, or other technical controls.</li>
          <li>No scraping the service or its content.</li>
          <li>No uploading content that&apos;s illegal, defamatory, or otherwise harmful.</li>
        </ul>

        <H2>Termination</H2>
        <p>
          You may stop using Brewmate at any time. We may terminate accounts that violate these terms. On termination,
          your data is deleted in accordance with the <a href="/privacy">Privacy Policy</a>.
        </p>

        <H2>Disclaimer of warranty</H2>
        <p>
          THE SERVICE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION
          WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
        </p>

        <H2>Limitation of liability</H2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, BREWMATE WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
          DAMAGES. OUR TOTAL LIABILITY IS CAPPED AT THE AMOUNT YOU&apos;VE PAID US IN THE LAST TWELVE MONTHS (CURRENTLY: ZERO).
        </p>

        <H2>Contact</H2>
        <p>Questions about these terms — <a href="mailto:hello@brewmate.app">hello@brewmate.app</a>.</p>

        <H2>Changes</H2>
        <p>
          We&apos;ll update the date at the top of this page when these terms change. Continued use after a change means you
          accept the updated terms.
        </p>
      </Prose>
    </article>
  );
}

function Prose({ children }: { children: React.ReactNode }) {
  return (
    <div className="space-y-5 text-[15px] md:text-[16px] leading-relaxed text-ink-2 [&_h2]:display [&_h2]:text-2xl [&_h2]:text-ink [&_h2]:mt-8 [&_h2]:mb-2 [&_b]:text-ink [&_a]:text-persimmon [&_a]:underline [&_a]:underline-offset-4 [&_ul]:list-disc [&_ul]:pl-5 [&_li]:my-1">
      {children}
    </div>
  );
}
function H2({ children }: { children: React.ReactNode }) {
  return <h2>{children}</h2>;
}
